---
domains:
  - docker.com
  - stackedit.io
  - docker.elastic.co.
  - container-registry.elastic.co.
  - docker-auth.elastic.co.
  - ansible.com
  - squadcast.com
  - scylladb.com
  - slack-msgs.com
  - slack-files.com
  - slack-imgs.com
  - slack-core.com
  - slack-redir.net
  - googleapis.com
  - trello.com
  - netdata.cloud
  - maxymiser.net
  - oracleinfinity.io
  - redis.io
  - snort.org
  - udemy.com
  - ton.org
  - katacoda.com
  - oreilly.com
  - enterprisedb.com
  - stackedit.io
  - algolianet.com
  - linuxacademy.com
  - freebitco.in
  - cloudsigma.com
  - hackernoon.com
  - rabbitmq.com
  - lenovo.com
  - mellanox.com
  - atlassian.com
  - emc.com
  - uber.com
  - rackspace.co
  - autopilothq.com
  - jadi.net
  - grafana.net
  - grafana.org
  - vmware.com
  - linode.com
  - saltstack.com
  - gitlab.com
  - slite.com
  - slack-edge.com
  - slack.com
  - winscp.net
  - sourceforge.net
  - centos.org
  - nvidia.com
  - pagerduty.com
  - opsgenie.com
  - oracle.com
  - adobe.com
  - kubernetes.io
  - youtube.com
  - projectcalico.org
  - quay.io
  - sysdig.com
  - robustperception.io
  - slack.engineering
  - gcr.io
  - atlassian.net
  - elastic.co
  - docker.com
  - docker.io
  - cloudflare-dns.com
  - cloudfront.net
  - amazonaws.com
  - mongodb.org
  - etcd.io
  - grafana.com
  - redislabs.com
  - mirror.bhs1.ovh.opendev.org
  - opendev.org
  - tvcdn.de
  - nordvpn.com
  - virtualbox.org
  - zabbix.com
  - hpe.com
  - ubnt-ut.com
  - discord.com
  - tenor.com
  - golang.org
  - amazon.com
  - fedoraproject.org
  - fastly.net
  - ceph.com
  - github.com
  - githubusercontent.com
  - openstack.org

working_dir: '/usr/local/src/marten'